# Generated by Django 2.2.4 on 2023-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_shows',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
