# Generated by Django 2.2.4 on 2023-06-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lasy_name',
            new_name='last_name',
        ),
    ]
